version: '3.7'

services:
  postgres:
    image: postgres:15
    restart: always
    hostname: devlinks-postgres
    container_name: devlinks-postgres
    env_file:
      - .env.test
    ports:
      - '5433:5432'
